In [11]:
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt


In [12]:
(X_train,y_train),(X_test,y_test)= keras.datasets.cifar10.load_data()

170508288/170498071 [==============================] - 2s 0us/step


In [13]:
X_train.shape

(50000, 32, 32, 3)

In [14]:
X_test.shape

(10000, 32, 32, 3)

In [15]:
#Data preprocessing
#Normalization
X_train= X_train/255.0
X_test= X_test/255.0

In [16]:
#sklearn expects i/p to be 2d array-model.fit(x_train,y_train)=>reshape to 2d array
nsamples, nX, ny, nrgb = X_train.shape
X_train2 = X_train.reshape((nsamples,nX*ny*nrgb))

In [19]:
#so,eventually,model.predict() should also be a 2d input
nsamples, nX, ny, nrgb = X_test.shape
X_test2 = X_test.reshape((nsamples,nX*ny*nrgb))

In [20]:
#RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train2,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier()

In [21]:
y_pred= model.predict(X_test2)
y_pred

array([3, 8, 8, ..., 3, 5, 7], dtype=uint8)

In [22]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy_score(y_pred,y_test)
print(classification_report(y_pred,y_test)) #47% accuracy on the test data

              precision    recall  f1-score   support

           0       0.56      0.55      0.56      1032
           1       0.55      0.52      0.54      1070
           2       0.34      0.38      0.35       893
           3       0.28      0.35      0.31       795
           4       0.41      0.40      0.41      1031
           5       0.39      0.41      0.40       954
           6       0.56      0.47      0.51      1182
           7       0.46      0.53      0.49       866
           8       0.60      0.59      0.60      1021
           9       0.55      0.48      0.51      1156

    accuracy                           0.47     10000
   macro avg       0.47      0.47      0.47     10000
weighted avg       0.48      0.47      0.47     10000



In [23]:
confusion_matrix(y_pred, y_test)

array([[564,  25,  98,  50,  59,  37,  10,  50,  91,  48],
       [ 42, 554,  40,  40,  21,  23,  36,  44,  97, 173],
       [ 60,  20, 336,  80, 138,  86,  83,  56,  17,  17],
       [ 18,  37,  76, 277,  49, 155,  67,  52,  26,  38],
       [ 35,  24, 149,  70, 414,  83, 120,  88,  25,  23],
       [ 21,  33,  70, 191,  58, 389,  54,  86,  31,  21],
       [ 26,  35, 118, 136, 138,  81, 560,  52,  12,  24],
       [ 26,  28,  57,  67,  75,  81,  22, 460,  20,  30],
       [152,  57,  29,  19,  27,  30,   7,  23, 605,  72],
       [ 56, 187,  27,  70,  21,  35,  41,  89,  76, 554]])

In [24]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train2,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [25]:
y_pred_knn= knn.predict(X_test2)
y_pred_knn

array([2, 8, 8, ..., 5, 6, 4], dtype=uint8)

In [26]:
accuracy_score(y_pred_knn,y_test)
print(classification_report(y_pred_knn,y_test)) #34% accuracy on the test data in knn

              precision    recall  f1-score   support

           0       0.52      0.40      0.45      1299
           1       0.20      0.70      0.30       280
           2       0.44      0.22      0.29      2013
           3       0.20      0.28      0.23       707
           4       0.52      0.23      0.32      2222
           5       0.20      0.40      0.27       504
           6       0.27      0.35      0.30       761
           7       0.20      0.70      0.31       281
           8       0.69      0.39      0.50      1749
           9       0.14      0.73      0.23       184

    accuracy                           0.34     10000
   macro avg       0.34      0.44      0.32     10000
weighted avg       0.45      0.34      0.35     10000



In [27]:
confusion_matrix(y_pred_knn,y_test)

array([[518, 118, 110,  66,  60,  63,  22,  78, 112, 152],
       [  7, 195,   2,   5,   0,   2,   1,   8,  10,  50],
       [118, 124, 437, 243, 268, 225, 271, 185,  47,  95],
       [ 12,  51,  50, 199,  33, 156,  56,  57,  34,  59],
       [ 46, 173, 250, 214, 521, 201, 319, 294,  69, 135],
       [  5,  32,  24, 102,  14, 204,  32,  60,  12,  19],
       [ 30,  55,  65, 108,  44,  80, 265,  48,  14,  52],
       [  5,   8,   7,  11,  11,  10,   1, 196,   7,  25],
       [255, 223,  53,  51,  48,  53,  32,  68, 688, 278],
       [  4,  21,   2,   1,   1,   6,   1,   6,   7, 135]])

In [28]:
from sklearn.tree import DecisionTreeClassifier
dtc= DecisionTreeClassifier()
dtc.fit(X_train2,y_train)

DecisionTreeClassifier()

In [29]:
y_pred_dtc= dtc.predict(X_test2)
y_pred_dtc

array([7, 1, 9, ..., 2, 3, 1], dtype=uint8)

In [30]:
accuracy_score(y_pred_dtc, y_test)
print(classification_report(y_pred_dtc, y_test)) #27% accuracu on the test data in decision tree

              precision    recall  f1-score   support

           0       0.35      0.33      0.34      1054
           1       0.27      0.29      0.28       959
           2       0.22      0.21      0.21      1057
           3       0.18      0.18      0.18       973
           4       0.23      0.22      0.22      1042
           5       0.22      0.22      0.22       989
           6       0.29      0.29      0.29      1014
           7       0.26      0.27      0.26       964
           8       0.38      0.38      0.38       994
           9       0.29      0.30      0.30       954

    accuracy                           0.27     10000
   macro avg       0.27      0.27      0.27     10000
weighted avg       0.27      0.27      0.27     10000



In [31]:
confusion_matrix(y_pred_dtc, y_test)

array([[350,  76,  97,  66,  55,  56,  41,  69, 155,  89],
       [ 63, 274,  47,  65,  43,  55,  57,  81, 109, 165],
       [ 84,  75, 220, 101, 160, 104, 122,  84,  46,  61],
       [ 52,  89,  86, 177,  76, 158, 125, 101,  42,  67],
       [ 69,  58, 156, 115, 227,  92, 135, 104,  46,  40],
       [ 56,  55, 110, 129, 113, 217,  97, 107,  52,  53],
       [ 41,  62, 108, 140, 127,  99, 291,  57,  28,  61],
       [ 65,  60,  84, 107, 113,  98,  61, 256,  37,  83],
       [143,  95,  39,  43,  41,  71,  28,  62, 380,  92],
       [ 77, 156,  53,  57,  45,  50,  43,  79, 105, 289]])

In [32]:
from sklearn.naive_bayes import GaussianNB
nb= GaussianNB()
nb.fit(X_train2, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [33]:
y_pred_nb= nb.predict(X_test2)
y_pred_nb

array([6, 8, 8, ..., 6, 5, 4], dtype=uint8)

In [34]:
accuracy_score(y_pred_nb, y_test)
print(classification_report(y_pred_nb,y_test)) #30% accuracy on the text data in nb

              precision    recall  f1-score   support

           0       0.49      0.27      0.35      1817
           1       0.17      0.41      0.24       405
           2       0.08      0.19      0.12       443
           3       0.08      0.25      0.12       305
           4       0.42      0.24      0.30      1737
           5       0.26      0.31      0.29       840
           6       0.47      0.25      0.33      1846
           7       0.13      0.42      0.20       310
           8       0.47      0.39      0.42      1219
           9       0.41      0.38      0.39      1078

    accuracy                           0.30     10000
   macro avg       0.30      0.31      0.28     10000
weighted avg       0.39      0.30      0.32     10000



In [35]:
confusion_matrix(y_pred_nb,y_test)

array([[494, 141, 225, 163,  86, 156, 106, 134, 168, 144],
       [ 20, 166,  24,  36,   8,  17,   2,  24,  41,  67],
       [ 39,  24,  83,  54,  57,  55,  60,  36,  18,  17],
       [ 10,  31,  15,  76,  26,  51,  18,  41,  17,  20],
       [ 84,  66, 292, 151, 417, 167, 228, 228,  56,  48],
       [ 34,  72,  48, 129,  38, 264,  46,  94,  83,  32],
       [ 50, 192, 209, 262, 265, 159, 467, 102,  39, 101],
       [  9,  19,  21,  26,  22,  36,  15, 131,   8,  23],
       [200, 121,  54,  34,  50,  57,  19,  72, 471, 141],
       [ 60, 168,  29,  69,  31,  38,  39, 138,  99, 407]])

Random Forest Classifier shows the best performance with 47% accuracy followed by KNN with 34% accuracy, NB with 30% accuracy, and Decision Tree with 27% accuracy. Thus, Random Forest exhibits the best performance and Decision Tree the worst.

However, all the Machine learning algorithms perform poorly as indicated by the accuracies. The highest is just 47% while Deep learning algorithms outsmart them exceptionally with accuracies mostly exceeding 90%!!!

That’s why I mentioned at the beginning itself that this work can only be used to compare a Deep Learning model and defend the DL model.

In [36]:
import cv2

In [37]:
img_path='/content/drive/MyDrive/Colab Notebooks/Bird.jpg'

In [38]:
img_arr=cv2.imread(img_path)
img_arr=cv2.resize(img_arr,(32,32))

In [39]:
#so,eventually,model.predict() should also be a 2d input
nX, ny, nrgb = img_arr.shape
img_arr2 = img_arr.reshape(1,(nX*ny*nrgb))

In [40]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [43]:
ans=model.predict(img_arr2)
print(classes[ans[0]])
#RandomForestClassifier

bird
